Quote.create!([
  {author: "A.A. Milne", quote: "The third-rate mind is only happy when it is thinking with the majority. The second-rate mind is only happy when it is thinking with the minority. The first-rate mind is only happy when it is thinking."},
  {author: "A.C. Green", quote: "Tough times don't last but tough people do."},
  {author: "Abba Eban", quote: "History teaches us that men and nations behave wisely once they have exhausted all other alternatives."},
  {author: "Abraham Lincoln", quote: "How many legs does a dog have, if you call the tail a leg? Four. Calling a tail a leg doesn't make it a leg."},
  {author: "Abraham Lincoln", quote: "Nearly all men can stand adversity, but if you want to test a man's character, give him power."},
  {author: "Abraham Lincoln", quote: "When I do good, I feel good; when I do bad, I feel bad, and that is my religion."},
  {author: "Abraham Lincoln", quote: "Better to remain silent and be thought a fool than to speak out and remove all doubt."},
  {author: "Abraham Lincoln", quote: "You can fool some of the people all of the time, and all of the people some of the time, but you can not fool all of the people all of the time."},
  {author: "Abraham Maslow", quote: "To the man who only has a hammer, everything he encounters begins to look like a nail."},
  {author: "Adlai Stevenson", quote: "My definition of a free society is a society where it is safe to be unpopular."},
  {author: "Adolph Hitler", quote: "It is always more difficult to fight against faith than against knowledge."},
  {author: "Albert Einstein", quote: "Education is what remains after one has forgotten what one has learned in school."},
  {author: "Albert Einstein", quote: "The person who reads too much and uses his brain too little will fall into lazy habits of thinking."},
  {author: "Albert Einstein", quote: "Insanity: doing the same thing over and over again and expecting different results."},
  {author: "Albert Einstein", quote: "Logic will get you from A to B. Imagination will take you everywhere."},
  {author: "Albert Einstein", quote: "Not everything that can be counted counts, and not everything that counts can be counted."},
  {author: "Albert Einstein", quote: "A clever person solves a problem. A wise person avoids it."},
  {author: "Albert Einstein", quote: "Imagination is more important than knowledge. For knowledge is limited to all we now know and understand, while imagination embraces the entire world, and all there ever will be to know and understand."},
  {author: "Albert Einstein", quote: "When you look at yourself from a universal standpoint, something inside always reminds or informs you that there are bigger and better things to worry about."},
  {author: "Albert Einstein", quote: "The only thing that interferes with my learning is my education."},
  {author: "Albert Einstein", quote: "The difference between genius and stupidity is that genius has its limits."},
  {author: "Albert Einstein", quote: "Time and space are modes by which we think and not conditions in which we live."},
  {author: "Albert Einstein", quote: "When you sit with a nice girl for two hours, you think it's only a minute. But when you sit on a hot stove for a minute, you think it's two hours. That's relativity."},
  {author: "Albert Einstein", quote: "Weakness of attitude becomes weakness of character."},
  {author: "Albert Guinon", quote: "There are people who, instead of listening to what is being said to them, are already listening to what they are going to say themselves."},
  {author: "Albert Guinon", quote: "When everyone is against you, it means that you are absolutely wrong-- or absolutely right."},
  {author: "Aldous Huxley", quote: "The charm of history and its enigmatic lesson consist in the fact that, from age to age, nothing changes and yet everything is completely different."},
  {author: "Alexander Pope", quote: "Blessed is the man who expects nothing, for he shall never be disappointed."},
  {author: "Alfred Adler", quote: "It is easier to fight for one's principles than to live up to them."},
  {author: "Alfred Montapert", quote: "Do not confuse motion and progress. A rocking horse keeps moving but does not make any progress."},
  {author: "Ambrose Bierce", quote: "War is God's way of teaching Americans geography."},
  {author: "Ambrose Redmoon", quote: "Courage is not the absence of fear, but rather the judgement that something else is more important than fear."},
  {author: "Anais Nin", quote: "We don't see things as they are. We see things as we are."},
  {author: "Andre Gide", quote: "It is better to fail at your own life than to succeed at someone else's."},
  {author: "Andre Gide", quote: "Believe those who are seeking the truth. Doubt those who find it."},
  {author: "Andre Gide", quote: "People cannot discover new lands until they have the courage to lose sight of the shore."},
  {author: "Andre Gide", quote: "There are admirable potentialities in every human being. Believe in your strength and your youth. Learn to repeat endlessly to yourself, 'It all depends on me.'"},
  {author: "Andrew Mathis", quote: "It is bad luck to be superstitious."},
  {author: "Antoine de Saint-Exupery", quote: "Perfection is achieved, not when there is nothing more to add, but when there is nothing left to take away."},
  {author: "Antoine de Saint-Exupery", quote: "You become responsible forever for what you've tamed."},
  {author: "Aristotle", quote: "It is the mark of an educated mind to be able to entertain a thought without accepting it."},
  {author: "Aristotle", quote: "We are what we repeatedly do; excellence, then, is not an act but a habit."},
  {author: "Aristotle", quote: "What lies in our power to do, lies in our power not to do."},
  {author: "Aristotle", quote: "I count him braver who overcomes his desires than him who conquers his enemies, for the hardest victory is over self."},
  {author: "Arnold Bennet", quote: "Having once decided to achieve a certain task, achieve it at all costs of tedium and distaste. The gain in self-confidence of having accomplished a tiresome labor is immense."},
  {author: "Arnold Palmer", quote: "Concentration comes out of a combination of confidence and hunger."},
  {author: "Arthur Schopenhauer", quote: "Talent hits a target no one else can hit; Genius hits a target no one else can see."},
  {author: "Arthur Schopenhauer", quote: "All truth passes through three stages. First, it is ridiculed. Second, it is violently opposed. Third, it is accepted as being self-evident."},
  {author: "Arthur Schopenhauer", quote: "Every nation ridicules other nations, and all are right."},
  {author: "Aryeh Frimer", quote: "I'd rather live with a good question than a bad answer."},
  {author: "Augustus William Hare", quote: "Seeking is not always the way to find."},
  {author: "Ayn Rand", quote: "The Argument from Intimidation is a confession of intellectual impotence."},
  {author: "B. F. Skinner", quote: "The real problem is not whether machines think but whether men do."},
  {author: "Baltasar Gracian", quote: "A wise man gets more use from his enemies than a fool from his friends."},
  {author: "Baltasar Gracian", quote: "Attempt easy tasks as if they were difficult, and difficult as if they were easy; in the one case that confidence may not fall asleep, in the other that it may not be dismayed."},
  {author: "Barry Goldwater", quote: "A government that is big enough to give you all you want is big enough to take it all away."},
  {author: "Barry LePatner", quote: "Good judgment comes from experience, and experience comes from bad judgment."},
  {author: "Basho", quote: "Do not seek to follow in the footsteps of the men of old; seek what they sought."},
  {author: "Benjamin Disraeli", quote: "Never apologize for showing feeling. When you do so, you apologize for truth."},
  {author: "Benjamin Disraeli", quote: "To govern men, you must either excel them in their accomplishments, or despise them."},
  {author: "Benjamin Franklin", quote: "Either write something worth reading or do something worth writing."},
  {author: "Benjamin Mays", quote: "The tragedy of life doesn't lie in not reaching your goal. The tragedy lies in having no goals to reach."},
  {author: "Bertrand Russell", quote: "The whole problem with the world is that fools and fanatics are always so certain of themselves, and wiser people so full of doubts."},
  {author: "Bertrand Russell", quote: "No one gossips about other people's secret virtues."},
  {author: "Bertrand Russell", quote: "The greatest challenge to any thinker is stating the problem in a way that will allow a solution."},
  {author: "Bertrand Russell", quote: "What men really want is not knowledge but certainty."},
  {author: "Bertrand Russell", quote: "The trouble with the world is that the stupid are cocksure and the intelligent are full of doubt."},
  {author: "Bill Cosby", quote: "I don't know the key to success, but the key to failure is trying to please everybody."},
  {author: "Bill Raeder", quote: "Thought is useful when it motivates for action, and a hindrance when it substitutes for action."},
  {author: "Bill Vaughn", quote: "We learn something every day, and lots of times it's that what we learned the day before was wrong."},
  {author: "Blaise Pascal", quote: "I have made this letter longer than usual because I lack the time to make it shorter."},
  {author: "Bo Bennett", quote: "A single question can be more influential than a thousand statements."},
  {author: "Bono", quote: "The less you know, the more you believe."},
  {author: "Buddha", quote: "The foot feels the foot when it feels the ground."},
  {author: "Cale Yarborough", quote: "Don't ever wrestle with a pig. You'll both get dirty, but the pig will enjoy it."},
  {author: "Carl Jung", quote: "Everything that irritates us about others can lead us to an understanding of ourselves."},
  {author: "Casey Stengel", quote: "Some people make things happen, some people watch things happen, and some ask what happened."},
  {author: "Catherine Aird", quote: "If you can't be a good example, then you'll just have to be a horrible warning."},
  {author: "Cecil Baxter", quote: "You don't get anything clean without getting something else dirty."},
  {author: "Chang-Tzu", quote: "Happiness is the absence of striving for happiness."},
  {author: "Charles Bukowski", quote: "The difference between a democracy and a dictatorship is that in a democracy you vote first and take orders later; in a dictatorship you don't have to waste your time voting."},
  {author: "Charles Kettering", quote: "An inventor is simply a fellow who doesn't take his education too seriously."},
  {author: "Charles Peters", quote: "Bureaucrats write memoranda both because they appear to be busy when they are writing and because the memos, once written, immediately become proof that they were busy."},
  {author: "Charles Wadsworth", quote: "By the time a man realizes that maybe his father was right, he usually has a son who thinks he's wrong."},
  {author: "Chuck Close", quote: "Inspiration is for amateurs. I just get to work."},
  {author: "Chuck Reid", quote: "In theory, there is no difference between theory and practice; In practice, there is."},
  {author: "Clarence Darrow", quote: "When I was a boy I was told that anybody could become President. Now I'm beginning to believe it."},
  {author: "Cyril Connolly", quote: "here are many who dare not kill themselves for fear of what the neighbors will say."},
  {author: "Dale Carnegie", quote: "Success is getting what you want. Happiness is wanting what you get."},
  {author: "Dame Edna Everage", quote: "Never be afraid to laugh at yourself, after all, you could be missing out on the joke of the century."},
  {author: "Dandemis", quote: "Do not condemn the judgement of another because it differs from your own. You may both be wrong."},
  {author: "Daniel Boorstin", quote: "The greatest obstacle to discovery is not ignorance - it is the illusion of knowledge."},
  {author: "David Allen", quote: "You can do anything, but not everything."},
  {author: "David Brin", quote: "It is said that power corrupts, but actually it's more true that power attracts the corruptible. The sane are usually attracted by other things than power."},
  {author: "David Cobitz", quote: "A committee can make a decision that is dumber than any of its members."},
  {author: "David Freeman", quote: "The more you know, the more you realise how much you don't know -- the less you know, the more you think you know."},
  {author: "David Freeman", quote: "The direct use of force is such a poor solution to any problem, it is generally employed only by small children and large nations."},
  {author: "David Lloyd George", quote: "Don't be afraid to take a big step if one is indicated. You can't cross a chasm in two small jumps."},
  {author: "David Richerby", quote: "The tooth fairy teaches children that they can sell body parts for money."},
  {author: "Dee Hock", quote: "Simple, clear purpose and principles give rise to complex and intelligent behavior. Complex rules and regulations give rise to simple and stupid behavior."},
  {author: "Dennis Waitley", quote: "The first step toward success will be the biggest one."},
  {author: "Dick Cavett", quote: "There's so much comedy on television. Does that cause comedy in the streets?"},
  {author: "Dick Cavett", quote: "If your parents never had children, chances are you won't, either."},
  {author: "Dick Cavett", quote: "It's a rare person who wants to hear what he doesn't want to hear."},
  {author: "Doug Horton", quote: "The art of simplicity is a puzzle of complexity."},
  {author: "Dwight Eisenhower", quote: "In preparing for battle I have always found that plans are useless, but planning is indispensable."},
  {author: "Edith Sitwell", quote: "I am patient with stupidity but not with those who are proud of it."},
  {author: "Edith Wharton", quote: "If only we'd stop trying to be happy we could have a pretty good time."},
  {author: "Edward Bulwer-Lytton", quote: "Talent does what it can; genius does what it must."},
  {author: "Edward Murrow", quote: "Just because your voice reaches halfway around the world doesn't mean you are wiser than when it reached only to the end of the bar."},
  {author: "Edward Phelps", quote: "The man who makes no mistakes does not usually make anything."},
  {author: "Edwin Schlossberg", quote: "The skill of writing is to create a context in which other people can think."},
  {author: "Emerson Pugh", quote: "If the human mind was simple enough to understand, we'd be too simple to understand it."},
  {author: "Emma Goldman", quote: "If voting changed anything, they'd make it illegal."},
  {author: "Epitectus", quote: "There is only one way to happiness and that is to cease worrying about things which are beyond the power of our will."},
  {author: "Eric Hoffer", quote: "You can discover what your enemy fears most by observing the means he uses to frighten you."},
  {author: "Eric Hoffer", quote: "When people are free to do as they please, they usually imitate each other."},
  {author: "Eric Hoffer", quote: "The opposite of the religious fanatic is not the fanatical atheist but the gentle cynic who cares not whether there is a god or not."},
  {author: "Erica Jong", quote: "Advice is what we ask for when we already know the answer but wish we didn't."},
  {author: "Ernest Hemingway", quote: "Courage is grace under pressure."},
  {author: "Eugene McCarthy", quote: "Being in politics is like being a football coach. You have to be smart enough to understand the game, and dumb enough to think it's important."},
  {author: "Evan Esar", quote: "Character is what you have left when you've lost everything you can lose."},
  {author: "Francois de la Rochefoucauld", quote: "We confess our little faults to persuade people that we have no large ones."},
  {author: "Francois de la Rochefoucauld", quote: "Crimes are made innocent, even virtuous, by their number and nature"},
  {author: "Frank Tibolt", quote: "We should be taught not to wait for inspiration to start a thing. Action always generates inspiration. Inspiration seldom generates action."},
  {author: "Frank Zappa", quote: "Writing about music is like dancing about architecture."},
  {author: "Franklin P. Jones", quote: "The trouble with being punctual is that nobody's there to appreciate it."},
  {author: "Franklin P. Jones", quote: "Experience is that marvelous thing that enables you to recognize a mistake when you make it again."},
  {author: "Friedrich Nietzche", quote: "Insanity in individuals is something rare - but in groups, parties, nations and epochs, it is the rule."},
  {author: "Friedrich Nietzche", quote: "The man of knowledge must be able not only to love his enemies but also to hate his friends."},
  {author: "Friedrich Nietzche", quote: "The surest way to corrupt a youth is to instruct him to hold in higher esteem those who think alike than those who think differently."},
  {author: "Friedrich Nietzche", quote: "There are no facts, only interpretations."},
  {author: "Friedrich Nietzche", quote: "I tell you: one must have chaos within oneself, to give birth to a dancing star."},
  {author: "Friedrich Nietzche", quote: "The last Christian died on the cross. (paraphrase)"},
  {author: "Friedrich Nietzche", quote: "What does not destroy me, makes me stronger."},
  {author: "Friedrich Nietzche", quote: "But thus do I counsel you, my friends: distrust all in whom the impulse to punish is powerful!"},
  {author: "Friedrich Nietzche", quote: "Thoughts are the shadows of our feelings — always darker, emptier, simpler."},
  {author: "Friedrich Nietzche", quote: "We are, all of us, growing volcanoes that approach the hour of their eruption; but how near or distant that is, nobody knows — not even God."},
  {author: "G. M. Trevelyan", quote: "Education... has produced a vast population able to read but unable to distinguish what is worth reading."},
  {author: "Galileo Galilei", quote: "I do not feel obliged to believe that the same God who has endowed us with sense, reason, and intellect has intended us to forgo their use."},
  {author: "Galileo Galilei", quote: "I have never met a man so ignorant that I couldn't learn something from him."},
  {author: "Georg Christoph Lichtenberg", quote: "Everyone is a genius at least once a year. The real geniuses simply have their bright ideas closer together."},
  {author: "George Bernard Shaw", quote: "My way of joking is to tell the truth. It is the funniest joke in the world."},
  {author: "George Bernard Shaw", quote: "The fact that a believer is happier than a skeptic is no more to the point than the fact that a drunken man is happier than a sober one."},
  {author: "George Bernard Shaw", quote: "Patriotism is your conviction that this country is superior to all other countries because you were born in it."},
  {author: "George Bernard Shaw", quote: "All great truths start as blasphemies"},
  {author: "George Orwell", quote: "All animals are equal but some animals are more equal than others."},
  {author: "George Satayana", quote: "Those who cannot remember the past are condemned to repeat it."},
  {author: "George Sheehan", quote: "To keep from decaying, to be a winner, the athlete must accept pain - not only accept it, but look for it, live with it, learn not to fear it."},
  {author: "George Wald", quote: "A physicist is an atom's way of knowing about atoms."},
  {author: "Georges Duhamel", quote: "I have too much respect for the idea of God to make it responsible for such an absurd world."},
  {author: "Groucho Marx", quote: "A child of five would understand this. Send someone to fetch a child of five."},
  {author: "Gustave Flaubert", quote: "There is no truth. There is only perception."},
  {author: "H.L. Mencken", quote: "All men are frauds. The only difference between them is that some admit it. I myself deny it."},
  {author: "Harold Stephens", quote: "There is a great difference between worry and concern. A worried person sees a problem, and a concerned person solves a problem."},
  {author: "Henri Bergson", quote: "Think like a man of action, act like a man of thought."},
  {author: "Henri Poincare", quote: "Science is facts; just as houses are made of stones, so is science made of facts; but a pile of stones is not a house and a collection of facts is not necessarily science."},
  {author: "Henrik Tikkanen", quote: "Truly great madness cannot be achieved without significant intelligence."},
  {author: "Henry David Thoreau", quote: "Every generation laughs at the old fashions, but follows religiously the new."},
  {author: "Henry David Thoreau", quote: "A man is rich in proportion to the number of things he can afford to let alone."},
  {author: "Henry David Thoreau", quote: "Men are probably nearer the central truth in their superstitions than in their science."},
  {author: "Henry Ford", quote: "Whether you think you can or think you can't -- you are right."},
  {author: "Hermann Hesse", quote: "If you hate a person, you hate something in him that is part of yourself. What isn't part of ourselves doesn't disturb us."},
  {author: "Horace Mann", quote: "Be ashamed to die until you have won some victory for humanity."},
  {author: "Horace Walpole", quote: "The whole secret of life is to be interested in one thing profoundly and in a thousand things well."},
  {author: "Immanuel Kant", quote: "Science is organized knowledge. Wisdom is organized life."},
  {author: "Issac Asimov", quote: "Part of the inhumanity of the computer is that, once it is competently programmed and working smoothly, it is completely honest."},
  {author: "Issac Newton", quote: "If I have seen further it is by standing on the shoulders of giants."},
  {author: "J.B.S. Haldane", quote: "Not only is the universe stranger (queerer) than we imagine, it is stranger (queerer) than we can imagine."},
  {author: "James Feibleman", quote: "A myth is a religion in which no one any longer believes."},
  {author: "James Thurber", quote: "It is better to know some of the questions than all of the answers."},
  {author: "Jawaharal Nehru", quote: "Life is like a game of cards. The hand that is dealt you is determinism; the way you play it is free will."},
  {author: "Jean Baptiste Moliere", quote: "Nearly all men die of their remedies, and not of their illnesses."},
  {author: "Jean Giraudoux", quote: "Only the mediocre are always at their best."},
  {author: "Jerome Blattner", quote: "A person who trusts no one can't be trusted."},
  {author: "Jiddu Krisnamurti", quote: "It is no measure of health to be well adjusted to a profoundly sick society."},
  {author: "Johann Lavater", quote: "Mistrust the man who finds everything good, the man who finds everything evil and still more the man who is indifferent to everything."},
  {author: "Johann von Goethe", quote: "The intelligent man finds almost everything ridiculous, the sensible man hardly anything."},
  {author: "Johann von Neumann", quote: "In mathematics you don't understand things. You just get used to them."},
  {author: "John F. Kennedy", quote: "Victory has a thousand fathers, but defeat is an orphan."},
  {author: "John Gardner", quote: "We are continually faced with a series of great opportunities brilliantly disguised as insoluble problems."},
  {author: "John Lennon", quote: "God is a concept by which we measure our pain."},
  {author: "John Lennon", quote: "Reality leaves a lot to the imagination."},
  {author: "John Lennon", quote: "Life is what happens to you while you're busy making other plans."},
  {author: "John Muir", quote: "When we try to pick out anything by itself, we find it hitched to everything else in the universe."},
  {author: "John Ruskin", quote: "What we think, or what we know, or what we believe is, in the end, of little consequence. The only consequence is what we do."},
  {author: "Johnathan Swift", quote: "No wise man ever wished to be younger."},
  {author: "Jose Marti", quote: "Man has to suffer. When he has no real afflictions, he invents some."},
  {author: "Joseph Baretti", quote: "I hate mankind, for I think myself one of the best of them, and I know how bad I am."},
  {author: "Jules de Gaultier", quote: "Imagination is the one weapon in the war against reality."},
  {author: "Jules Renard", quote: "Laziness is nothing more than the habit of resting before you get tired."},
  {author: "Lance Armstrong", quote: "Anything is possible, but you have to believe and you have to fight."},
  {author: "Lao-Tzu", quote: "Watch your thoughts; they become words. Watch your words; they become actions. Watch your actions; they become habits. Watch your habits; they become character. Watch your character; it becomes your destiny."},
  {author: "Lao-Tzu", quote: "A journey of a thousand miles begins with a single step."},
  {author: "Larry Bossidy", quote: "Truth over Harmony."},
  {author: "Lee Simonson", quote: "Any event, once it has occurred, can be made to appear inevitable by a competent historian."},
  {author: "Leo Tolstoy", quote: "Everyone thinks of changing the world, but no one thinks of changing himself."},
  {author: "Leonardo da Vinci", quote: "Simplicity is the ultimate sophistication."},
  {author: "Lin Yutang", quote: "Besides the noble art of getting things done, there is the noble art of leaving things undone. The wisdom of life consists in the elimination of nonessentials."},
  {author: "Lin-Chi", quote: "When hungry, eat your rice; when tired, close your eyes. Fools may laugh at me, but wise men will know what I mean."},
  {author: "Linus Pauling", quote: "The best way to have a good idea is to have lots of ideas."},
  {author: "Lois McMaster Bujold", quote: "There are always survivors at a massacre. Among the victors, if nowhere else."},
  {author: "Lord Thomas Macaulay", quote: "The highest proof of virtue is to possess boundless power without abusing it."},
  {author: "Lou Holtz", quote: "Life is ten percent what happens to you and ninety percent how you respond to it."},
  {author: "M.H. McKee", quote: "Wisdom is knowing the right path to take… Integrity is taking it."},
  {author: "Mabel Newcomber", quote: "It is more important to know where you are going than to get there quickly."},
  {author: "Mahatma Gandhi", quote: "God has no religion"},
  {author: "Malcolm Forbes", quote: "Education's purpose is to replace an empty mind with an open one."},
  {author: "Marcel Proust", quote: "The real voyage of discovery consists not in seeking new lands but seeing with new eyes."},
  {author: "Margaret Millar", quote: "Most conversations are simply monologues delivered in the presence of witnesses."},
  {author: "Marilyn Manson", quote: "Times have not become more violent. They have just become more televised."},
  {author: "Mario Andretti", quote: "If everything's under control, you're going too slow."},
  {author: "Mark Twain", quote: "All you need in this life is ignorance and confidence; then success is sure."},
  {author: "Mark Twain", quote: "The difference between the right word and the almost right word is the difference between lightning and a lightning bug."},
  {author: "Mark Twain", quote: "Never argue with a fool, onlookers may not be able to tell the difference."},
  {author: "Mark Twain", quote: "Most people are bothered by those passages of Scripture they do not understand, but the passages that bother me are those I do understand."},
  {author: "Mark Twain", quote: "It is by the goodness of God that in our country we have those three unspeakably precious things: freedom of speech, freedom of conscience, and the prudence never to practice either of them."},
  {author: "Mark Twain", quote: "Whenever you find that you are on the side of the majority, it is time to reform."},
  {author: "Marquis de Vauvenargues", quote: "When a thought is too weak to be expressed simply, simply drop it."},
  {author: "Michael Jordan", quote: "I can accept failure, but I can't accept not trying."},
  {author: "Michel de Montaigne", quote: "A man who fears suffering is already suffering from what he fears."},
  {author: "Muhammad Ali", quote: "Champions aren't made in the gyms. Champions are made from something they have deep inside them—a desire, a dream, a vision."},
  {author: "Napoleon Bonaparte", quote: "Never ascribe to malice, that which can be explained by incompetence."},
  {author: "Napoleon Bonaparte", quote: "History is the version of past events that people have decided to agree upon."},
  {author: "Napoleon Bonaparte", quote: "Never interrupt your enemy when he is making a mistake."},
  {author: "Nathaniel LeTonnerre", quote: "I doubt one could live in the darkness, but one could probably survive."},
  {author: "Niels Bohr", quote: "The opposite of a correct statement is a false statement.  But the opposite of a profound truth may well be another profound truth."},
  {author: "Norman Mailer", quote: "There is no greater impotence in all the world like knowing you are right and that the wave of the world is wrong, yet the wave crashes upon you."},
  {author: "Olin Miller", quote: "You probably wouldn't worry about what people think of you if you could know how seldom they do."},
  {author: "Orville Mars", quote: "The little I know I owe to my ignorance."},
  {author: "Oscar Wilde", quote: "Imagination was given to man to compensate him for what he is not, and a sense of humor was provided to console him for what he is."},
  {author: "Oscar Wilde", quote: "Anybody can make history. Only a great man can write it."},
  {author: "Oscar Wilde", quote: "We are all in the gutter, but some of us are looking at the stars."},
  {author: "Oscar Wilde", quote: "Experience is the name everyone gives to their mistakes."},
  {author: "Oscar Wilde", quote: "Education is an admirable thing. But it is well to remember from time to time that nothing that is worth knowing can be taught."},
  {author: "Oscar Wilde", quote: "Religions die when they are proved to be true. Science is the record of dead religions."},
  {author: "Oscar Wilde", quote: "The old believe everything; the middle-aged suspect everything; the young know everything."},
  {author: "Oscar Wilde", quote: "Truth, in the matters of religion, is simply the opinion that has survived."},
  {author: "Oscar Wilde", quote: "The one duty we owe to history is to rewrite it."},
  {author: "Plato", quote: "Wise men talk because they have something to say; fools, because they have to say something."},
  {author: "Proverb (African)", quote: "Do not look where you fell, but where you slipped."},
  {author: "Proverb (Buddhist)", quote: "When the student is ready the teacher will appear."},
  {author: "Proverb (Chinese)", quote: "He who asks is a fool for five minutes, but he who does not ask remains a fool forever."},
  {author: "Proverb (Chinese)", quote: "One dog barks at something. And a hundred dogs bark at the sound."},
  {author: "Proverb (Chinese)", quote: "I hear: I forget / I see: I remember / I do: I understand"},
  {author: "Proverb (Dutch)", quote: "In prosperity, caution; in adversity, patience."},
  {author: "Proverb (German)", quote: "No answer is also an answer."},
  {author: "Proverb (Italian)", quote: "Once the game is over, the King and the pawn go back in the same box."},
  {author: "Proverb (Jewish)", quote: "The man who has confidence in himself gains the confidence of others."},
  {author: "Proverb (Norwegian)", quote: "Heroism consists of hanging on one minute longer."},
  {author: "Proverb (Zen)", quote: "The obstacle is the path."},
  {author: "Proverb (Zen)", quote: "Before enlightnment, chop wood, carry water. After enlightnment, chop wood, carry water."},
  {author: "Ralph Sockman", quote: "The test of courage comes when we are in the minority. The test of tolerance comes when we are in the majority."},
  {author: "Ralph Waldo Emerson", quote: "What I must do is all that concerns me, not what the people think."},
  {author: "Ralph Waldo Emerson", quote: "If I have lost confidence in myself, I have the universe against me."},
  {author: "Ray Bradbury", quote: "You have to know how to accept rejection and reject acceptance."},
  {author: "Rene Decartes", quote: "Each problem that I solved became a rule which served afterwards to solve other problems."},
  {author: "Rita Mae Brown", quote: "One of the keys to happiness is a bad memory."},
  {author: "Robert Fripp", quote: "Understanding is simple. Knowing is complicated."},
  {author: "Robert Heinlein", quote: "Progress isn't made by early risers. It's made by lazy men trying to find easier ways to do something."},
  {author: "Robert Humphrey", quote: "An undefined problem has an infinite number of solutions."},
  {author: "Robert von Musli", quote: "One does what one is; one becomes what one does."},
  {author: "Ron Jeffries", quote: "If there's only one answer, then this must not be a very interesting topic."},
  {author: "Rosalynn Carter", quote: "You have to have confidence in your ability, and then be tough enough to follow through."},
  {author: "Sam Keen", quote: "What shapes our lives are the questions we ask, refuse to ask, or never think to ask."},
  {author: "Samuel Johnson", quote: "Self-confidence is the first requisite to great undertakings."},
  {author: "Samuel Johnson", quote: "What is written without effort is in general read without pleasure."},
  {author: "Shunryu Suzuki", quote: "In the beginner's mind there are many possibilities, but in the expert's there are few."},
  {author: "Simone de Beauvoir", quote: "If you live long enough, you'll see that every victory turns into a defeat."},
  {author: "Sir Arthur Conan Doyle", quote: "If you can eliminate all the other choices, the remaining choice, no matter how improbable, is the answer."},
  {author: "Sir Edmund Hillary", quote: "It is not the mountain we conquer, but ourselves."},
  {author: "Socrates", quote: "The unexamined life is not worth living."},
  {author: "Socrates", quote: "I know nothing except the fact of my ignorance."},
  {author: "Soren Kierkegaard", quote: "Life can only be understood backwards; but it must be lived forwards."},
  {author: "Soren Kierkegaard", quote: "The task must be made difficult, for only the difficult inspires the noble-hearted."},
  {author: "Soren Kierkegaard", quote: "The truth is a trap: you can not get it without it getting you; you cannot get the truth by capturing it, only by its capturing you."},
  {author: "Soren Kierkegaard", quote: "Worldly wisdom thinks that love is a relationship between man and man. Christianity teaches that love is a relationship between: man-God-man, that is, that God is the middle term."},
  {author: "Stanislaus I", quote: "To believe with certainty we must begin with doubting."},
  {author: "Stephen Covey", quote: "The best way to predict the future is to create it."},
  {author: "Steve Jones", quote: "I run with my head, my heart and my guts, because physically, I don't think I've got a great deal of talent or ability. I started at the bottom and worked up."},
  {author: "Steve Prefontaine", quote: "A man can fail many times, but he isn't a failure until he begins to blame somebody else."},
  {author: "Steve Prefontaine", quote: "Most people run a race to see who is fastest. I run a race to see who has the most guts."},
  {author: "Sun Tzu", quote: "Victorious warriors win first and then go to war, while defeated warriors go to war first and then seek to win."},
  {author: "Sun Tzu", quote: "The best victory is when the opponent surrenders of its own accord before there are any actual hostilities...It is best to win without fighting."},
  {author: "Suzanne Necker", quote: "Fortune does not change men, it unmasks them."},
  {author: "Sydney Harris", quote: "When I hear somebody sigh, 'Life is hard,' I am always tempted to ask, 'Compared to what?'"},
  {author: "T.H. Huxley", quote: "Try to learn something about everything and everything about something."},
  {author: "T.H. Huxley", quote: "God give me strength to face a fact though it slay me."},
  {author: "T.S. Eliot", quote: "Only those who will risk going too far can possibly find out how far they can go."},
  {author: "Tallulah Bankhead", quote: "If I had to live my life again, I'd make the same mistakes, only sooner."},
  {author: "Terry Josephson", quote: "No matter where you go or what you do, you live your entire life within the confines of your head."},
  {author: "Theodore Geisel", quote: "Be who you are and say what you feel, because those who mind don't matter and those who matter don't mind."},
  {author: "Theodore Roethke", quote: "By daily dying I have come to be."},
  {author: "Theodore Roosevelt", quote: "Far better is it to dare mighty things, to win glorious triumphs, even though checkered by failure, than to rank with those poor spirits who neither enjoy nor suffer much, because they live in a gray twilight that knows not victory nor defeat."},
  {author: "Thomas Edison", quote: "I have not failed. I've just found 10,000 ways that won't work."},
  {author: "Thomas Szasz", quote: "When a person can no longer laugh at himself, it is time for others to laugh at him."},
  {author: "Tom Fleming", quote: "Somewhere in the world someone is training when you are not. When you race him, he will win."},
  {author: "Unknown", quote: "We don't see the things the way they are. We see things the way WE are."},
  {author: "Victor Hugo", quote: "I don't mind what Congress does, as long as they don't do it in the streets and frighten the horses."},
  {author: "Vince Lombardi", quote: "Winning is a habit. Unfortunately so is losing."},
  {author: "Vince Lombardi", quote: "In great attempts, it is glorious even to fail."},
  {author: "William Wordsworth", quote: "We feel that we are greater than we know."},
  {author: "Wilson Mizner", quote: "I respect faith, but doubt is what gets you an education."},
  {author: "Winston Churchill", quote: "A pessimist sees the difficulty in every opportunity, an optimist sees the opportunity in every difficulty."},
  {author: "Winston Churchill", quote: "If you are going through hell, keep going."},
  {author: "Winston Churchill", quote: "I have nothing to offer but blood, toil, tears, and sweat."},
  {author: "Winston Churchill", quote: "Never give in — never, never, never, never, in nothing great or small, large or petty, never give in except to convictions of honour and good sense. Never yield to force; never yield to the apparently overwhelming might of the enemy."},
  {author: "Winston Churchill", quote: "Now this is not the end. It is not even the beginning of the end. But it is, perhaps, the end of the beginning."},
  {author: "Winston Churchill", quote: "An appeaser is one who feeds a crocodile, hoping it will eat him last."},
  {author: "Winston Churchill", quote: "Success is not final, failure is not fatal: it is the courage to continue that counts."},
  {author: "Winston Churchill", quote: "History will be kind to me for I intend to write it."},
  {author: "Winston Churchill", quote: "You have enemies? Good. That means you've stood up for something, sometime in your life."},
  {author: "Winston Churchill", quote: "It is not enough that we do our best; sometimes we must do what is required."},
  {author: "Winston Churchill", quote: "Success is stumbling from failure to failure with no loss of enthusiasm."}
])
User.create!([
  {provider: "twitter", uid: "2398359236", name: "Ana Ciocarlan", oauth_token: nil, oauth_secret: nil}
])
